theme: minima

---
title: De gustibus non est disputandum
author:
    name: sing1estep
    email: "sing1estep@supernot.org"
description: -
  Information of questionable value
social_links:
    - title: Sing1estep's GitHub
      icon: github
      url: "https://github.com/sing1estep"
---
